part of 'workflow_bloc.dart';

enum QualityCheckStatus { initial, loading, success, failure }
enum PostQualityCheckStatus { initial, loading, success, failure }

enum CycleCountStatus { initial, loading, success, failure }

class WorkflowState {
   List<QualityCheckTask> qualityCheckTasks;
   List<QualityCheckTask>? completedQualityChecks;

  final List<CycleCountTask> cycleCountTasks;
  bool? selectedAllQualityCheckTasks;
  bool? selectedAllCycleCountTasks;
  final QualityCheckStatus? getQualityCheckStatus;
  final CycleCountStatus? getCycleCountStatus;
  int? buttonIndex;
  Set<String>? selectedQaulityCheckTasks ;
  PostQualityCheckStatus? postQualityCheckStatus;
  int? pendingQualityCheckPageCount;
  int? completedQualityCheckPageCount;

  WorkflowState(
      {this.getQualityCheckStatus,
      this.getCycleCountStatus,
      required this.qualityCheckTasks,
      required this.cycleCountTasks,
      this.selectedAllQualityCheckTasks,
      this.selectedAllCycleCountTasks,
      this.selectedQaulityCheckTasks,
      this.buttonIndex,
      this.postQualityCheckStatus,
      this.completedQualityChecks,
      this.pendingQualityCheckPageCount,
      this.completedQualityCheckPageCount,
      });

  factory WorkflowState.initial() {
    return WorkflowState(
        getQualityCheckStatus: QualityCheckStatus.initial,
        getCycleCountStatus: CycleCountStatus.initial,
        selectedQaulityCheckTasks: {},
        completedQualityChecks: [],
        qualityCheckTasks: [
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001066',
          //     status: 'Received',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Beer',
          //     itemDescription: 'Beer',
          //     currQty: 100,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161024,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 100,
          //     uom2: 'units',
          //     receivedQty: 100,
          //     uom3: 'units',
          //     poNbr: '310',
          //     receivedShipment: 'SHPAID00000356',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/7/2024 13:41',
          //     receivingUser: 'krishna_vamsi',
          //     shipmentType: 'Purchase Order',
          //     weight: 0,
          //     uomwt: 'KG',
          //     volume: 0,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001063',
          //     status: 'Received',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Soda',
          //     itemDescription: 'Soda',
          //     currQty: 150,
          //     uom: 'units',
          //     location: 'Aisle 3',
          //     batchNbr: 161025,
          //     expiryDate: '12/31/2025',
          //     manufactureDate: '10/01/2024',
          //     origQty: 150,
          //     uom2: 'units',
          //     receivedQty: 150,
          //     uom3: 'units',
          //     poNbr: '311',
          //     receivedShipment: 'SHPAID00000357',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/8/2024 09:30',
          //     receivingUser: 'john_doe',
          //     shipmentType: 'Purchase Order',
          //     weight: 10,
          //     uomwt: 'KG',
          //     volume: 1000,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001068',
          //     status: 'Pending',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Whiskey',
          //     itemDescription: 'Whiskey',
          //     currQty: 200,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161026,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 200,
          //     uom2: 'units',
          //     receivedQty: 200,
          //     uom3: 'units',
          //     poNbr: '312',
          //     receivedShipment: 'SHPAID00000358',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/9/2024 11:15',
          //     receivingUser: 'jane_smith',
          //     shipmentType: 'Purchase Order',
          //     weight: 15,
          //     uomwt: 'KG',
          //     volume: 1500,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001069',
          //     status: 'Received',
          //     qcStatus: 'QC Approved',
          //     itemCode: 'Vodka',
          //     itemDescription: 'Vodka Bottle - 750ml',
          //     currQty: 120,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161027,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 120,
          //     uom2: 'units',
          //     receivedQty: 120,
          //     uom3: 'units',
          //     poNbr: '313',
          //     receivedShipment: 'SHPAID00000359',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/10/2024 14:00',
          //     receivingUser: 'alice_jones',
          //     shipmentType: 'Purchase Order',
          //     weight: 8,
          //     uomwt: 'KG',
          //     volume: 800,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001056',
          //     status: 'Received',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Beer',
          //     itemDescription: 'Beer',
          //     currQty: 100,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161024,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 100,
          //     uom2: 'units',
          //     receivedQty: 100,
          //     uom3: 'units',
          //     poNbr: '310',
          //     receivedShipment: 'SHPAID00000356',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/7/2024 13:41',
          //     receivingUser: 'krishna_vamsi',
          //     shipmentType: 'Purchase Order',
          //     weight: 0,
          //     uomwt: 'KG',
          //     volume: 0,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001067',
          //     status: 'Received',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Soda',
          //     itemDescription: 'Soda',
          //     currQty: 150,
          //     uom: 'units',
          //     location: 'Aisle 3',
          //     batchNbr: 161025,
          //     expiryDate: '12/31/2025',
          //     manufactureDate: '10/01/2024',
          //     origQty: 150,
          //     uom2: 'units',
          //     receivedQty: 150,
          //     uom3: 'units',
          //     poNbr: '311',
          //     receivedShipment: 'SHPAID00000357',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/8/2024 09:30',
          //     receivingUser: 'john_doe',
          //     shipmentType: 'Purchase Order',
          //     weight: 10,
          //     uomwt: 'KG',
          //     volume: 1000,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001061',
          //     status: 'Pending',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Whiskey',
          //     itemDescription: 'Whiskey',
          //     currQty: 200,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161026,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 200,
          //     uom2: 'units',
          //     receivedQty: 200,
          //     uom3: 'units',
          //     poNbr: '312',
          //     receivedShipment: 'SHPAID00000358',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/9/2024 11:15',
          //     receivingUser: 'jane_smith',
          //     shipmentType: 'Purchase Order',
          //     weight: 15,
          //     uomwt: 'KG',
          //     volume: 1500,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001099',
          //     status: 'Received',
          //     qcStatus: 'QC Approved',
          //     itemCode: 'Vodka',
          //     itemDescription: 'Vodka Bottle - 750ml',
          //     currQty: 120,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161027,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 120,
          //     uom2: 'units',
          //     receivedQty: 120,
          //     uom3: 'units',
          //     poNbr: '313',
          //     receivedShipment: 'SHPAID00000359',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/10/2024 14 :00',
          //     receivingUser: 'alice_jones',
          //     shipmentType: 'Purchase Order',
          //     weight: 8,
          //     uomwt: 'KG',
          //     volume: 800,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001070',
          //     status: 'Received',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Rum',
          //     itemDescription: 'Rum Bottle - Dark Rum',
          //     currQty: 90,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161028,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 90,
          //     uom2: 'units',
          //     receivedQty: 90,
          //     uom3: 'units',
          //     poNbr: '314',
          //     receivedShipment: 'SHPAID00000360',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/11/2024 15 :20',
          //     receivingUser: 'bob_brown',
          //     shipmentType: 'Purchase Order',
          //     weight: 7,
          //     uomwt: 'KG',
          //     volume: 700,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001071',
          //     status: 'Pending',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Tequila',
          //     itemDescription: 'Tequila Bottle - Silver',
          //     currQty: 80,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161029,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 80,
          //     uom2: 'units',
          //     receivedQty: 80,
          //     uom3: 'units',
          //     poNbr: '315',
          //     receivedShipment: 'SHPAID00000361',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/12/2024 16 :45',
          //     receivingUser: 'charlie_white',
          //     shipmentType: 'Purchase Order',
          //     weight: 6,
          //     uomwt: 'KG',
          //     volume: 600,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001072',
          //     status: 'Received',
          //     qcStatus: 'QC Approved',
          //     itemCode: 'Gin',
          //     itemDescription: 'Gin Bottle - London Dry',
          //     currQty: 110,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161030,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 110,
          //     uom2: 'units',
          //     receivedQty: 110,
          //     uom3: 'units',
          //     poNbr: '316',
          //     receivedShipment: 'SHPAID00000362',
          //     putawayType: 'PUTAWAY1',
          //     createTimestamp: '10/13/2024 11 :00',
          //     receivingUser: 'david_black',
          //     shipmentType: 'Purchase Order',
          //     weight: 9,
          //     uomwt: 'KG',
          //     volume: 900,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //     isChecked: false,
          //     facility: 'DUTY-PAID',
          //     lpnNbr: 'IBPAIDL00001073',
          //     status: 'Pending',
          //     qcStatus: 'QC Pending',
          //     itemCode: 'Cider',
          //     itemDescription: 'Cider Bottle - Apple Flavored',
          //     currQty: 75,
          //     uom: 'units',
          //     location: '',
          //     batchNbr: 161031,
          //     expiryDate: '',
          //     manufactureDate: '',
          //     origQty: 75,
          //     uom2: 'units',
          //     receivedQty: 75,
          //     uom3: 'units',
          //     poNbr: '317',
          //     receivedShipment: 'SHPAID00000363',
          //     putawayType: 'PUTAWAY2',
          //     createTimestamp: '10/14/2024 14 :30',
          //     receivingUser: 'emily_green',
          //     shipmentType: 'Purchase Order',
          //     weight: 5,
          //     uomwt: 'KG',
          //     volume: 500,
          //     uomvol: 'CM3'),
          // QualityCheckTask(
          //   isChecked: false,
          //   facility: 'DUTY-PAID',
          //   lpnNbr: 'IBPAIDL00001074',
          //   status: 'Received',
          //   qcStatus: 'QC Approved',
          //   itemCode: 'Brandy',
          //   itemDescription: 'Brandy Bottle - VSOP',
          //   currQty: 60,
          //   uom: 'units',
          //   location: '',
          //   batchNbr: 161032,
          //   expiryDate: '',
          //   manufactureDate: '',
          //   origQty: 60,
          //   uom2: 'units',
          //   receivedQty: 60,
          //   uom3: 'units ',
          //   poNbr: '318 ',
          //   receivedShipment: 'SHPAID00000364 ',
          //   putawayType: 'PUTAWAY1 ',
          //   createTimestamp: '10/15/2024 09:00 ',
          //   receivingUser: 'frank_yellow ',
          //   shipmentType: 'Purchase Order',
          //   weight: 4.5,
          //   uomwt: 'KG ',
          //   volume: 450,
          //   uomvol: 'CM³ ',
          // ),
          // QualityCheckTask(
          //   isChecked: false,
          //   facility: 'DUTY-PAID ',
          //   lpnNbr: 'IBPAIDL00001075 ',
          //   status: 'Pending ',
          //   qcStatus: 'QC Pending ',
          //   itemCode: 'Absinthe ',
          //   itemDescription: 'Absinthe Bottle - Green Fairy ',
          //   currQty: 30,
          //   uom: ' units ',
          //   location: '',
          //   batchNbr: 161033,
          //   expiryDate: '',
          //   manufactureDate: '',
          //   origQty: 30,
          //   uom2: ' units ',
          //   receivedQty: 30,
          //   uom3: ' units ',
          //   poNbr: '319',
          //   receivedShipment: 'SHPAID00000365',
          //   putawayType: ' PUTAWAY2 ',
          //   createTimestamp: '10 /16 /2024 13 :00 ',
          //   receivingUser: 'george_blue',
          //   shipmentType: ' Purchase Order ',
          //   weight: 3.5,
          //   uomwt: ' KG ',
          //   volume: 350,
          //   uomvol: ' CM³ ',
          // )
       
        ],

        cycleCountTasks: [
          CycleCountTask(
            isChecked: false,
            facility: "DUTY-PAID",
            companyID: "M10",
            grpNbr: 71579,
            task: "TSPAID00002227",
            totalExpectedQuantity: 49946,
            uom: "units",
            totalCountedQty: 950,
            uom2: "units",
            totalAdjustedQty: -48996,
            uom3: "units",
            totalAdjustedCost: -57996,
            status: "Pending",
            location: "SP-ARE-PAR-TS",
            createUser: "rama_chandar",
            createTimestamp: "10/22/2024 8:04",
          ),
          CycleCountTask(
            isChecked: false,
            facility: "DUTY-PAID",
            companyID: "M11",
            grpNbr: 71580,
            task: "TSPAID00002228",
            totalExpectedQuantity: 30000,
            uom: "units",
            totalCountedQty: 15000,
            uom2: "units",
            totalAdjustedQty: -15000,
            uom3: "units",
            totalAdjustedCost: -20000,
            status: "Approved",
            location: "SP-ARE-PAR-TS",
            createUser: "john_doe",
            createTimestamp: "10/23/2024 9:15",
          ),
          CycleCountTask(
            isChecked: false,
            facility: "DUTY-PAID",
            companyID: "M12",
            grpNbr: 71581,
            task: "TSPAID00002229",
            totalExpectedQuantity: 60000,
            uom: "units",
            totalCountedQty: 60000,
            uom2: "units",
            totalAdjustedQty: 0,
            uom3: "units",
            totalAdjustedCost: 0,
            status: "Rejected",
            location: "SP-ARE-PAR-TS",
            createUser: "jane_smith",
            createTimestamp: "10/24/2024 10:30",
          ),
          CycleCountTask(
              isChecked: false,
              facility: "DUTY-PAID",
              companyID: "M13",
              grpNbr: 71582,
              task: "TSPAID00002230",
              totalExpectedQuantity: -1000,
              uom: "units",
              totalCountedQty: -500,
              uom2: "units",
              totalAdjustedQty: -500,
              uom3: "units",
              totalAdjustedCost: -600,
              status: "Pending",
              location: "SP-ARE-PAR-TS",
              createUser: "alice_jones",
              createTimestamp: "10/25/2024 11:45"),

          CycleCountTask(
              isChecked: false,
              facility: "DUTY-PAID",
              companyID: "M14",
              grpNbr: null,
              task: "TSPAID00002231",
              totalExpectedQuantity: null,
              uom: "units",
              totalCountedQty: null,
              uom2: "units",
              totalAdjustedQty: null,
              uom3: "units",
              totalAdjustedCost: null,
              status: "Approved",
              location: "SP-ARE-PAR-TS",
              createUser: "bob_brown",
              createTimestamp: "10/26/2024 12:00"),

          CycleCountTask(
              isChecked: false,
              facility: "DUTY-PAID",
              companyID: "M15",
              grpNbr: null,
              task: "TSPAID00002232",
              totalExpectedQuantity: null,
              uom: "units",
              totalCountedQty: null,
              uom2: "units",
              totalAdjustedQty: null,
              uom3: "units",
              totalAdjustedCost: null,
              status: "Pending",
              location: "SP-ARE-PAR-TS",
              createUser: "charlie_black",
              createTimestamp: "10/27/2024 1:30"),

          CycleCountTask(
              isChecked: false,
              facility: "DUTY-PAID",
              companyID: "M16",
              grpNbr: null,
              task: "TSPAID00002233",
              totalExpectedQuantity: null,
              uom: "units",
              totalCountedQty: null,
              uom2: "units",
              totalAdjustedQty: null,
              uom3: "units",
              totalAdjustedCost: null,
              status: "Rejected",
              location: "SP-ARE-PAR-TS",
              createUser: "david_green",
              createTimestamp: "10/28/2024 2:15"),

          CycleCountTask(
              isChecked: false,
              facility: "DUTY-PAID",
              companyID: "M17",
              grpNbr: null,
              task: "TSPAID00002234",
              totalExpectedQuantity: null,
              uom: "units",
              totalCountedQty: null,
              uom2: "units",
              totalAdjustedQty: null,
              uom3: "units",
              totalAdjustedCost: null,
              status: "Pending",
              location: "SP-ARE-PAR-TS",
              createUser: "eve_white",
              createTimestamp: "10/29/2024 3:00"),

          CycleCountTask(
              isChecked: false,
              facility: 'DUTY-PAID', // Example with no adjustments
              companyID: 'M18', // Example with no adjustments
              grpNbr: null, // Group number can be null
              task: 'TSPAID00002239',
              totalExpectedQuantity: null, // Expected quantity can be null
              uom: null, // UOM can be null
              totalCountedQty: null, // Counted quantity can be null
              uom2: null, // Second UOM can be null
              totalAdjustedQty: null, // Adjusted quantity can be null
              uom3: null, // Third UOM can be null
              totalAdjustedCost: null, // Adjusted cost can be null
              status: 'Pending', // Status can also be null
              location: 'SP-ARE-PAR-TS', // Location can also be null
              createUser: 'frank_yellow', // Create user can also be null
              createTimestamp: '10/30/2024 4:45'), // Create timestamp can also be null
        ],
        selectedAllQualityCheckTasks: false,
        selectedAllCycleCountTasks: false,
        buttonIndex: 0,
        );
  }

  WorkflowState copyWith({
    QualityCheckStatus? getQualityCheckStatus,
    CycleCountStatus? getCycleCountStatus,
    List<QualityCheckTask>? qualityCheckTasks,
    List<CycleCountTask>? cycleCountTasks,
    bool? selectedAllQualityCheckTasks,
    bool? selectedAllCycleCountTasks,
    int? buttonIndex,
    Set<String>? selectedQaulityCheckTasks,
    PostQualityCheckStatus? postQualityCheckStatus,
    List<QualityCheckTask>? completedQualityChecks,
    int? pendingQualityCheckPageCount,
    int? completedQualityCheckPageCount,
  }) {
    return WorkflowState(
      getQualityCheckStatus: getQualityCheckStatus ?? this.getQualityCheckStatus,
      getCycleCountStatus: getCycleCountStatus ?? this.getCycleCountStatus,
      qualityCheckTasks: qualityCheckTasks ?? this.qualityCheckTasks,
      cycleCountTasks: cycleCountTasks ?? this.cycleCountTasks,
      selectedAllQualityCheckTasks: selectedAllQualityCheckTasks ?? this.selectedAllQualityCheckTasks,
      selectedAllCycleCountTasks: selectedAllCycleCountTasks ?? this.selectedAllCycleCountTasks,
      buttonIndex: buttonIndex ?? this.buttonIndex,
      selectedQaulityCheckTasks: selectedQaulityCheckTasks ?? this.selectedQaulityCheckTasks,
        postQualityCheckStatus: postQualityCheckStatus ?? this.postQualityCheckStatus,
        completedQualityChecks: completedQualityChecks ?? this.completedQualityChecks,
        pendingQualityCheckPageCount: pendingQualityCheckPageCount ?? this.pendingQualityCheckPageCount, 
        completedQualityCheckPageCount: completedQualityCheckPageCount ?? this.completedQualityCheckPageCount,
    );
  }
}
